package projet.suiviapprenti.DAL.Entitys;
// Generated 23 févr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classe generated by hbm2java
 */
@Entity
@Table(name = "classe", catalog = "suiviapprenti")
public class Classe implements java.io.Serializable {

	private Integer idclasse;
	private String nom;
	private int annee;
	private Set<Apprenti> apprentis = new HashSet<Apprenti>(0);
	private Set<SeanceEdt> seanceEdts = new HashSet<SeanceEdt>(0);
	private Set<ClasseProfesseur> classeProfesseurs = new HashSet<ClasseProfesseur>(0);

	public Classe() {
	}

	public Classe(String nom, int annee) {
		this.nom = nom;
		this.annee = annee;
	}

	public Classe(String nom, int annee, Set<Apprenti> apprentis, Set<SeanceEdt> seanceEdts,
			Set<ClasseProfesseur> classeProfesseurs) {
		this.nom = nom;
		this.annee = annee;
		this.apprentis = apprentis;
		this.seanceEdts = seanceEdts;
		this.classeProfesseurs = classeProfesseurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idclasse", unique = true, nullable = false)
	public Integer getIdclasse() {
		return this.idclasse;
	}

	public void setIdclasse(Integer idclasse) {
		this.idclasse = idclasse;
	}

	@Column(name = "nom", nullable = false, length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "annee", nullable = false)
	public int getAnnee() {
		return this.annee;
	}

	public void setAnnee(int annee) {
		this.annee = annee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classe")
	public Set<Apprenti> getApprentis() {
		return this.apprentis;
	}

	public void setApprentis(Set<Apprenti> apprentis) {
		this.apprentis = apprentis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classe")
	public Set<SeanceEdt> getSeanceEdts() {
		return this.seanceEdts;
	}

	public void setSeanceEdts(Set<SeanceEdt> seanceEdts) {
		this.seanceEdts = seanceEdts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classe")
	public Set<ClasseProfesseur> getClasseProfesseurs() {
		return this.classeProfesseurs;
	}

	public void setClasseProfesseurs(Set<ClasseProfesseur> classeProfesseurs) {
		this.classeProfesseurs = classeProfesseurs;
	}

}
