package projet.suiviapprenti.DAL.Entitys;
// Generated 23 févr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClasseProfesseur generated by hbm2java
 */
@Entity
@Table(name = "classeProfesseur", catalog = "suiviapprenti")
public class ClasseProfesseur implements java.io.Serializable {

	private Integer idclasseProfesseur;
	private Classe classe;
	private Professeur professeur;

	public ClasseProfesseur() {
	}

	public ClasseProfesseur(Classe classe, Professeur professeur) {
		this.classe = classe;
		this.professeur = professeur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idclasseProfesseur", unique = true, nullable = false)
	public Integer getIdclasseProfesseur() {
		return this.idclasseProfesseur;
	}

	public void setIdclasseProfesseur(Integer idclasseProfesseur) {
		this.idclasseProfesseur = idclasseProfesseur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idclasse", nullable = false)
	public Classe getClasse() {
		return this.classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprofesseur", nullable = false)
	public Professeur getProfesseur() {
		return this.professeur;
	}

	public void setProfesseur(Professeur professeur) {
		this.professeur = professeur;
	}

}
