package projet.suiviapprenti.DAL.Entitys;
// Generated 23 févr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.map.annotate.JsonView;

import projet.suiviapprenti.REST.JSON.JSONViews;

/**
 * Entreprise generated by hbm2java
 */
@Entity
@Table(name = "entreprise", catalog = "suiviapprenti")
public class Entreprise implements java.io.Serializable {

	@JsonView(JSONViews.AutocompleteEntreprise.class) private Integer identreprise;
	@JsonView(JSONViews.AutocompleteEntreprise.class) private Coordonnees coordonnees;
	@JsonView(JSONViews.AutocompleteEntreprise.class) private String nomEntreprise;
	@JsonView(JSONViews.AutocompleteEntreprise.class) private String branche;
	@JsonView(JSONViews.AutocompleteEntreprise.class) private int nbSalaries;
	private Set<ParcoursPostBts> parcoursPostBtses = new HashSet<ParcoursPostBts>(0);
	private Set<Taxe> taxes = new HashSet<Taxe>(0);
	private Set<Apprenti> apprentis = new HashSet<Apprenti>(0);

	public Entreprise() {
	}

	public Entreprise(Coordonnees coordonnees, String nomEntreprise, String branche, int nbSalaries) {
		this.coordonnees = coordonnees;
		this.nomEntreprise = nomEntreprise;
		this.branche = branche;
		this.nbSalaries = nbSalaries;
	}

	public Entreprise(Coordonnees coordonnees, String nomEntreprise, String branche, int nbSalaries,
			Set<ParcoursPostBts> parcoursPostBtses, Set<Taxe> taxes, Set<Apprenti> apprentis) {
		this.coordonnees = coordonnees;
		this.nomEntreprise = nomEntreprise;
		this.branche = branche;
		this.nbSalaries = nbSalaries;
		this.parcoursPostBtses = parcoursPostBtses;
		this.taxes = taxes;
		this.apprentis = apprentis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "identreprise", unique = true, nullable = false)
	public Integer getIdentreprise() {
		return this.identreprise;
	}

	public void setIdentreprise(Integer identreprise) {
		this.identreprise = identreprise;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.ALL)
	@JoinColumn(name = "idCoordonnees", nullable = false)
	public Coordonnees getCoordonnees() {
		return this.coordonnees;
	}

	public void setCoordonnees(Coordonnees coordonnees) {
		this.coordonnees = coordonnees;
	}

	@Column(name = "nomEntreprise", nullable = false, length = 80)
	public String getNomEntreprise() {
		return this.nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

	@Column(name = "branche", nullable = false, length = 80)
	public String getBranche() {
		return this.branche;
	}

	public void setBranche(String branche) {
		this.branche = branche;
	}

	@Column(name = "nbSalaries", nullable = false)
	public int getNbSalaries() {
		return this.nbSalaries;
	}

	public void setNbSalaries(int nbSalaries) {
		this.nbSalaries = nbSalaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entreprise")
	public Set<ParcoursPostBts> getParcoursPostBtses() {
		return this.parcoursPostBtses;
	}

	public void setParcoursPostBtses(Set<ParcoursPostBts> parcoursPostBtses) {
		this.parcoursPostBtses = parcoursPostBtses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entreprise")
	public Set<Taxe> getTaxes() {
		return this.taxes;
	}

	public void setTaxes(Set<Taxe> taxes) {
		this.taxes = taxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entreprise")
	public Set<Apprenti> getApprentis() {
		return this.apprentis;
	}

	public void setApprentis(Set<Apprenti> apprentis) {
		this.apprentis = apprentis;
	}

}
