package projet.suiviapprenti.DAL.Entitys;
// Generated 23 févr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * ParcoursPostBts generated by hbm2java
 */
@Entity
@Table(name = "parcoursPostBTS", catalog = "suiviapprenti")
public class ParcoursPostBts implements java.io.Serializable {

	private Integer idparcoursPostBts;
	private Apprenti apprenti;
	private Entreprise entreprise;
	private String fonction;
	private Date dateDebut;

	public ParcoursPostBts() {
	}

	public ParcoursPostBts(Apprenti apprenti, String fonction, Date dateDebut) {
		this.apprenti = apprenti;
		this.fonction = fonction;
		this.dateDebut = dateDebut;
	}

	public ParcoursPostBts(Apprenti apprenti, Entreprise entreprise, String fonction, Date dateDebut) {
		this.apprenti = apprenti;
		this.entreprise = entreprise;
		this.fonction = fonction;
		this.dateDebut = dateDebut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idparcoursPostBTS", unique = true, nullable = false)
	public Integer getIdparcoursPostBts() {
		return this.idparcoursPostBts;
	}

	public void setIdparcoursPostBts(Integer idparcoursPostBts) {
		this.idparcoursPostBts = idparcoursPostBts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idApprenti", nullable = false)
	public Apprenti getApprenti() {
		return this.apprenti;
	}

	public void setApprenti(Apprenti apprenti) {
		this.apprenti = apprenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@Cascade(CascadeType.SAVE_UPDATE)
	@JoinColumn(name = "idEntreprise")
	public Entreprise getEntreprise() {
		return this.entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
	}

	@Column(name = "fonction", nullable = false, length = 45)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateDebut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

}
