package projet.suiviapprenti.DAL.Entitys;
// Generated 15 mars 2016 11:09:10 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ParticipationSeance generated by hbm2java
 */
@Entity
@Table(name = "participationSeance", catalog = "suiviapprenti")
public class ParticipationSeance implements java.io.Serializable {

	private Integer idparticipationSeance;
	private Apprenti apprenti;
	private Seance seance;
	private Double retard;
	private String absent;
	private Date dateSeance;
	private String salle;
	private double nbreHeuresAbs;

	public ParticipationSeance() {
	}

	public ParticipationSeance(Apprenti apprenti, Seance seance, String absent, Date dateSeance, double nbreHeuresAbs) {
		this.apprenti = apprenti;
		this.seance = seance;
		this.absent = absent;
		this.dateSeance = dateSeance;
		this.nbreHeuresAbs = nbreHeuresAbs;
	}

	public ParticipationSeance(Apprenti apprenti, Seance seance, Double retard, String absent, Date dateSeance,
			String salle, double nbreHeuresAbs) {
		this.apprenti = apprenti;
		this.seance = seance;
		this.retard = retard;
		this.absent = absent;
		this.dateSeance = dateSeance;
		this.salle = salle;
		this.nbreHeuresAbs = nbreHeuresAbs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idparticipationSeance", unique = true, nullable = false)
	public Integer getIdparticipationSeance() {
		return this.idparticipationSeance;
	}

	public void setIdparticipationSeance(Integer idparticipationSeance) {
		this.idparticipationSeance = idparticipationSeance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idApprenti", nullable = false)
	public Apprenti getApprenti() {
		return this.apprenti;
	}

	public void setApprenti(Apprenti apprenti) {
		this.apprenti = apprenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSeance", nullable = false)
	public Seance getSeance() {
		return this.seance;
	}

	public void setSeance(Seance seance) {
		this.seance = seance;
	}

	@Column(name = "retard", precision = 22, scale = 0)
	public Double getRetard() {
		return this.retard;
	}

	public void setRetard(Double retard) {
		this.retard = retard;
	}

	@Column(name = "absent", nullable = false, length = 4)
	public String getAbsent() {
		return this.absent;
	}

	public void setAbsent(String absent) {
		this.absent = absent;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateSeance", nullable = false, length = 10)
	public Date getDateSeance() {
		return this.dateSeance;
	}

	public void setDateSeance(Date dateSeance) {
		this.dateSeance = dateSeance;
	}

	@Column(name = "salle", length = 15)
	public String getSalle() {
		return this.salle;
	}

	public void setSalle(String salle) {
		this.salle = salle;
	}

	@Column(name = "nbreHeuresAbs", nullable = false, precision = 22, scale = 0)
	public double getNbreHeuresAbs() {
		return this.nbreHeuresAbs;
	}

	public void setNbreHeuresAbs(double nbreHeuresAbs) {
		this.nbreHeuresAbs = nbreHeuresAbs;
	}

}
