package projet.suiviapprenti.DAL.Entitys;
// Generated 23 févr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professeur generated by hbm2java
 */
@Entity
@Table(name = "professeur", catalog = "suiviapprenti")
public class Professeur implements java.io.Serializable {

	private Integer idprofesseur;
	private String codeRfid;
	private String login;
	private String mdp;
	private String nom;
	private String prenom;
	private Set<Seance> seances = new HashSet<Seance>(0);
	private Set<SeanceEdt> seanceEdts = new HashSet<SeanceEdt>(0);
	private Set<ClasseProfesseur> classeProfesseurs = new HashSet<ClasseProfesseur>(0);

	public Professeur() {
	}

	public Professeur(String codeRfid, String login, String mdp, String nom) {
		this.codeRfid = codeRfid;
		this.login = login;
		this.mdp = mdp;
		this.nom = nom;
	}

	public Professeur(String codeRfid, String login, String mdp, String nom, String prenom, Set<Seance> seances,
			Set<SeanceEdt> seanceEdts, Set<ClasseProfesseur> classeProfesseurs) {
		this.codeRfid = codeRfid;
		this.login = login;
		this.mdp = mdp;
		this.nom = nom;
		this.prenom = prenom;
		this.seances = seances;
		this.seanceEdts = seanceEdts;
		this.classeProfesseurs = classeProfesseurs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idprofesseur", unique = true, nullable = false)
	public Integer getIdprofesseur() {
		return this.idprofesseur;
	}

	public void setIdprofesseur(Integer idprofesseur) {
		this.idprofesseur = idprofesseur;
	}

	@Column(name = "codeRFID", nullable = false, length = 45)
	public String getCodeRfid() {
		return this.codeRfid;
	}

	public void setCodeRfid(String codeRfid) {
		this.codeRfid = codeRfid;
	}

	@Column(name = "login", nullable = false, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "mdp", nullable = false, length = 45)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@Column(name = "nom", nullable = false, length = 80)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 80)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professeur")
	public Set<Seance> getSeances() {
		return this.seances;
	}

	public void setSeances(Set<Seance> seances) {
		this.seances = seances;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professeur")
	public Set<SeanceEdt> getSeanceEdts() {
		return this.seanceEdts;
	}

	public void setSeanceEdts(Set<SeanceEdt> seanceEdts) {
		this.seanceEdts = seanceEdts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professeur")
	public Set<ClasseProfesseur> getClasseProfesseurs() {
		return this.classeProfesseurs;
	}

	public void setClasseProfesseurs(Set<ClasseProfesseur> classeProfesseurs) {
		this.classeProfesseurs = classeProfesseurs;
	}

}
