package projet.suiviapprenti.DAL.Entitys;
// Generated 15 mars 2016 11:09:10 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SeanceEdt generated by hbm2java
 */
@Entity
@Table(name = "seanceEDT", catalog = "suiviapprenti")
public class SeanceEdt implements java.io.Serializable {

	private Integer idseanceEdt;
	private Classe classe;
	private Professeur professeur;
	private Date heureDebut;
	private Date heureFin;
	private String jour;
	private String matiere;

	public SeanceEdt() {
	}

	public SeanceEdt(Classe classe, Professeur professeur, Date heureDebut, Date heureFin, String jour) {
		this.classe = classe;
		this.professeur = professeur;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
		this.jour = jour;
	}

	public SeanceEdt(Classe classe, Professeur professeur, Date heureDebut, Date heureFin, String jour,
			String matiere) {
		this.classe = classe;
		this.professeur = professeur;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
		this.jour = jour;
		this.matiere = matiere;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idseanceEDT", unique = true, nullable = false)
	public Integer getIdseanceEdt() {
		return this.idseanceEdt;
	}

	public void setIdseanceEdt(Integer idseanceEdt) {
		this.idseanceEdt = idseanceEdt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idclasse", nullable = false)
	public Classe getClasse() {
		return this.classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprofesseur", nullable = false)
	public Professeur getProfesseur() {
		return this.professeur;
	}

	public void setProfesseur(Professeur professeur) {
		this.professeur = professeur;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heureDebut", nullable = false, length = 8)
	public Date getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(Date heureDebut) {
		this.heureDebut = heureDebut;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heureFin", nullable = false, length = 8)
	public Date getHeureFin() {
		return this.heureFin;
	}

	public void setHeureFin(Date heureFin) {
		this.heureFin = heureFin;
	}

	@Column(name = "jour", nullable = false, length = 3)
	public String getJour() {
		return this.jour;
	}

	public void setJour(String jour) {
		this.jour = jour;
	}

	@Column(name = "matiere", length = 45)
	public String getMatiere() {
		return this.matiere;
	}

	public void setMatiere(String matiere) {
		this.matiere = matiere;
	}

}
