package projet.suiviapprenti.DAL.Entitys;
// Generated 23 févr. 2016 13:46:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taxe generated by hbm2java
 */
@Entity
@Table(name = "taxe", catalog = "suiviapprenti")
public class Taxe implements java.io.Serializable {

	private Integer idtaxe;
	private Apprenti apprenti;
	private Entreprise entreprise;
	private Date annee;
	private int montant;
	private String section;

	public Taxe() {
	}

	public Taxe(Apprenti apprenti, Entreprise entreprise, Date annee, int montant, String section) {
		this.apprenti = apprenti;
		this.entreprise = entreprise;
		this.annee = annee;
		this.montant = montant;
		this.section = section;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtaxe", unique = true, nullable = false)
	public Integer getIdtaxe() {
		return this.idtaxe;
	}

	public void setIdtaxe(Integer idtaxe) {
		this.idtaxe = idtaxe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idApprenti", nullable = false)
	public Apprenti getApprenti() {
		return this.apprenti;
	}

	public void setApprenti(Apprenti apprenti) {
		this.apprenti = apprenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEntreprise", nullable = false)
	public Entreprise getEntreprise() {
		return this.entreprise;
	}

	public void setEntreprise(Entreprise entreprise) {
		this.entreprise = entreprise;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "annee", nullable = false, length = 10)
	public Date getAnnee() {
		return this.annee;
	}

	public void setAnnee(Date annee) {
		this.annee = annee;
	}

	@Column(name = "montant", nullable = false)
	public int getMontant() {
		return this.montant;
	}

	public void setMontant(int montant) {
		this.montant = montant;
	}

	@Column(name = "section", nullable = false, length = 40)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

}
